# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  fabric-ca:

services:
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:1.4.3
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer1-org1:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      # TLS Section
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/crypto-config/org1/peer1/tls-msp/tlscacerts/tls-0-0-0-0-7054.pem
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/crypto-config/org1/peer1/tls-msp/signcerts/cert.pem
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/crypto-config/org1/peer1/tls-msp/keystore/key.pem
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/crypto-config/org1/admin/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: /bin/bash
    volumes:
      - /tmp/hyperledger:/opt/gopath/src/github.com/hyperledger/fabric/crypto-config
      - ./chaincode:/opt/gopath/src/github.com/hyperledger/fabric/chaincode
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/channel-artifacts
    networks:
      - fabric-ca